language: php

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - stan
  - test
  - style

jobs:
  include:
    - stage: Stan

      php: 7.2

      before_install:
        - phpenv config-rm xdebug.ini
        - composer validate

      install:
        - composer install

      script:
        - vendor/bin/phpstan analyse -l max -c phpstan.neon src tests

    - &TEST

      stage: Test

      php: 7.1

      env: WITH_LOWEST=true

      before_install:
        - phpenv config-rm xdebug.ini
        - composer validate

      install:
        - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; fi
        - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
        - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

      script:
        - vendor/bin/phpunit

    - <<: *TEST

      php: 7.1

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOWEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.2

      env: WITH_HIGHEST=true

    - stage: Style

      php: 7.1

      before_install:
        - phpenv config-rm xdebug.ini

      install:
        - composer install

      script:
        - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
